### ISSUE TITLE
firefox 59.0.2

### ISSUE THREAD

**Issue by jgroenveld** [trueos/freebsd-ports#106]
I was able to update TrueOS' /usr/ports/www/firefox Makefile and patches with the SVN checkout of FreeBSD's.
However, make fails here:

[root@trueos] /usr/ports/www/firefox# make
===>  Building for firefox-59.0.2,1
gmake[2]: Entering directory '/usr/ports/www/firefox/work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5'
/usr/ports/www/firefox/work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5/client.mk:40: /.mozconfig-client-mk: No such file or directory
gmake[2]: *** No rule to make target '/.mozconfig-client-mk'.  Stop.
gmake[2]: Leaving directory '/usr/ports/www/firefox/work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/www/firefox
*** Error code 1

Stop.
make: stopped in /usr/ports/www/firefox

The fugly hack:
$ cd work/mozilla-release-239e434d6d2b8e1e2b697c3416d1e96d48fe98e5
$ gmake

John
groenveld@acm.org

**Comment by jbeich** [comment]
Apply 9e2b8bf876ca
