### ISSUE TITLE
patches for /net/igmpproxy

### ISSUE THREAD

**Issue by ahtotaat** [trueos/freebsd-ports#68]
Please add the patches from [https://github.com/pfsense/FreeBSD-ports/tree/devel/net/igmpproxy/files](url) into trueos-ports repository as well.

They seem to apply just fine "as is" and address some of the bugs pfSense guys fixed for themselves.

**Comment by Mrt134** [comment]
@beanpole135 and I looked into it briefly, and it appears better to open an issue in the FreeBSD Bug tracker (https://bugs.freebsd.org/bugzilla/) to request the port be updated there. This helps the entire FreeBSD community and helps keep TrueOS from adding too many customised elements apart from base FreeBSD.
