### ISSUE TITLE
Get iohyve into stable again

### ISSUE THREAD

**Issue by jmdavis** [trueos/freebsd-ports#81]
I don't know if this is the right place to bring this up or not, but since it's about a port, this at least seems like the right place. In any case, iohyve is currently missing from TrueOS stable (I don't know if it's in unstable or not). Based on the changelog on freshports ( http://www.freshports.org/sysutils/iohyve/ ), I'd guess that the reason for that is because iohyve wasn't building previously. But now it is - or at least, the changelog claims that it was fixed for 12.0-CURRENT. S,o it would be really nice if we could get iohyve back into TrueOS stable without having to wait until the next full, 6-month release - and since it wasn't actually included before, presumably, adding it now won't disrupt anything (especially since it uses shell and AFAIK depends on nothing outside of base).

**Comment by Mrt134** [comment]
It's recommended to put this issue in the trueos-core repo, as that is the "central" area for TrueOS project issues, but don't worry about it.

Thanks for the request - we'll take a look!

**Comment by Mrt134** [comment]
Small update: we're still having build failures for iohyve in STABLE as of Aug 3, UNSTABLE doesn't appear to be attempting to build it at all. I haven't gotten a response yet from the others if this is intended or not, will update again when I do.

**Comment by Mrt134** [comment]
Update: iohyve is building and included again in the latest UNSTABLE (released over the weekend of 8/18). I'll try to get it included as a backport in the next small STABLE update.

**Comment by beanpole135** [comment]
iohyve packages are currently available in the latest STABLE (17.12) and UNSTABLE repositories for TrueOS.
