### ISSUE TITLE
xrdp/open-rc service (start and stop) doesn't work

### ISSUE THREAD

**Issue by ichibiri** [trueos/freebsd-ports#86]
`FreeBSD trost 12.0-CURRENT FreeBSD 12.0-CURRENT #10 d26791952(trueos-stable-17.12): Sat Dec  9 18:10:09 UTC 2017 `

Edit:
in **/usr/local/etc/init.d/xrdp**

```

rc-service -v xrdp start
 * Caching service dependencies ...
 * $xrdp_sesman_enable is not set properly                                                                          [ ok ]
 * Executing: /libexec/rc/sh/openrc-run.sh /libexec/rc/sh/openrc-run.sh /usr/local/etc/init.d/xrdp start
 * $xrdp_sesman_enable is not set properly

Generating 512 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to /usr/local/etc/xrdp/rsakeys.ini

Unknown Parameter
xrdp -h for help

```
`
**rc-status**

`xrdp                                                                                                        [  started  ]`

No, the **xrdp and xrdp-sesman** daemons don't start!

**xrdp** and **xrdp-sesman** start ok from cli input

**Comment by beanpole135** [comment]
Fixed!
https://github.com/trueos/freebsd-ports/commit/56ab73a04f63c34966b984cbf727ff032732045c

**Comment by beanpole135** [comment]
If you want to test that out right now, just copy these two files into your /usr/local/etc/init.d folder:
1. https://github.com/trueos/freebsd-ports/blob/56ab73a04f63c34966b984cbf727ff032732045c/net/xrdp/files/openrc-xrdp.in
2. https://github.com/trueos/freebsd-ports/blob/56ab73a04f63c34966b984cbf727ff032732045c/net/xrdp/files/openrc-xrdp-sesman.in

Open the two files and replace every instance of "%%PREFIX%%" with "/usr/local", then run `chmod 755 /usr/local/etc/init.d/xrdp*` to ensure they are executable.
After that you can do the standard `service xrdp [start/stop]` or `service xrdp-sesman [start/stop]`
